### ISSUE TITLE
RoR group project: set up your Kanban board Submission

### ISSUE THREAD

**Issue by fmanimashaun** [fmanimashaun/recipe-app#12]
Project link: https://github.com/users/fmanimashaun/projects/14

Number of team members: 2

**Comment by skyv26** [comment]
## Hi @fmanimashaun, 

Good job so far 👍🏻 
There are some issues that you still need to work on task assignment but you are almost done to start working on the project!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTY5MTMxNDUzNWFmNjU5MmFjOWZjY2IyMDIyY2RhNWFlYmU4NjdlNCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/Xfb7kQ0VhUIrpiuGx1/giphy.gif)

## Highlights
- Link is provided and information is shared.

## Required Changes ♻️

- [x] Please assign the card to your partner, it seems like you are a team of two members but you didn't assign any task or card to your partner. Even the task points are also not equally assigned. Please make the changes as per the `setup` instructions and if your partner is not responding then please reach out to the student success without thinking twice and any delay.

#### Cheers, and Happy coding!👏👏👏

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by franclobo** [comment]
Hi @gdvl777 and @fmanimashaun, 

# STATUS: APPROVED 😃 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Equal distribution of activities ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
